version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gym-app
    container_name: gym-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=FitLifeGym
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - gym-network

  db:
    image: mysql:8.0
    container_name: gym-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  dbdata: 