services:
  - type: web
    name: fitlife-gym
    env: docker
    plan: free
    repo: https://github.com/Mrgig7/FitLife-Gym
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: fitlife-gym
          property: url
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: fitlife-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fitlife-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: fitlife-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: fitlife-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fitlife-db
          property: password

databases:
  - name: fitlife-db
    plan: free 